name: pancreatic-bn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - numpy=1.21.5
  - pandas=1.4.2
  - networkx=2.7.1
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - pip
  - pip:
    - tqdm
    - ruamel.yaml
    - click
